[CA-122] README.md update
CodingGardenCommunity/app-backend pull request #70
Opened 2019-08-25 08:03 UTC by CodingCreate101

Relatively detailed Documentation for new contributors.

2019-08-25 08:06 UTC, CodingCreate101 commented
To make review easier, this is how it looks on Github:

[![License: MIT](https://img.shields.io/badge/License-MIT-yellow.svg)](https://opensource.org/licenses/MIT) ![GitHub package.json version](https://img.shields.io/github/package-json/v/CodingGardenCommunity/app-backend.svg) ![Travis (.org) branch](https://img.shields.io/travis/CodingGardenCommunity/app-backend/develop.svg) ![Libraries.io dependency status for GitHub repo](https://img.shields.io/librariesio/github/CodingGardenCommunity/app-backend.svg) ![GitHub contributors](https://img.shields.io/github/contributors/CodingGardenCommunity/app-backend.svg) ![GitHub commit activity](https://img.shields.io/github/commit-activity/m/CodingGardenCommunity/app-backend.svg)

# Coding Garden Community App API

This repository contains the source files and documentation for the API of the
Coding Garden Community App. For more information about the Community App
please visit the [App Wiki](https://github.com/CodingGardenCommunity/app-wiki/wiki).

## Running the API locally

> **NOTE:** If you find yourself in some trouble going through this, reach out to us on our [Discord server](https://github.com/CodingGardenCommunity/app-wiki/wiki/Getting-Involved).

### Prerequisites

1. **NodeJS:** <br>
   Please install [NodeJS >= 10.15.0](https://nodejs.org/en/download/), which also automatically installs the [npm](https://www.npmjs.org), Node Package Manager. If you already have them, you are good to go.

1. **EditorConfig:** <br>
   Please visit [EditorConfig](https://editorconfig.org/) -> `Download a Plugin` section and scroll through to see if you need to install an additional Plugin/Extension for your code editor or IDE. If your IDE needs one, you should be able to find a link to that plugin/extension on that page.

   This prerequisite is directly related to: [`.editorconfig`](https://github.com/CodingGardenCommunity/app-backend/blob/develop/.editorconfig) in the root directory of this project.

   **_More About EditorConfig:_** <br>
   EditorConfig helps maintain consistent coding styles for multiple developers working on the same project across various editors and IDEs. The EditorConfig project consists of a file format for defining coding styles and a collection of text editor plugins that enable editors to read the file format and adhere to defined styles. EditorConfig files are easily readable and they work nicely with version control systems.

There are multiple ways to run the API locally:

- [Via Yarn or NPM](#via-yarn-or-npm)
- [Via Docker](#via-docker)

---

### Via Yarn or NPM

Once you have the [Prerequisites](#prerequisites) covered:

1. [Clone](https://help.github.com/articles/cloning-a-repository/) this repository from GitHub onto your local computer.

   ```
   $ git clone https://github.com/CodingGardenCommunity/app-backend.git
   ```

1. Navigate into the project folder and install all of its necessary dependencies with NPM or Yarn.

   ```
   $ cd app-backend
   $ npm install // or yarn install
   ```

1. Install MongoDB and make sure it's running

   - For Mac OSX with [homebrew](http://brew.sh/): `brew install mongodb` then `brew services start mongodb`
   - For Windows and Linux: [MongoDB Installation](https://docs.mongodb.com/manual/installation/)

1. Make a copy of `.env.sample` and rename it to `.env`. You can do so with this simple command:

   > **NOTE:** If you are using Windows Command Prompt, you need to use `copy` instead of `cp`. <br>

   ```sh
   $ cp .env.example .env
   ```

   You don't need to change any values in `.env` file. The default values work well for development purposes.

1. Once you have MongoDB and `.env` file ready, populate some data in your local Database to work with

   ```sh
   npm run seed
   ```

1. To make sure everything is setup properly, run tests.

   ```sh
   npm run test
   ```

   If all tests pass(they will), we can safely conclude that setup is complete and its working as expected. Wooh!!

1. Once that's done, tap your back. You are ready to start contributing :)

   ```sh
   npm run dev // To start your local-development-server.
   ```

You can now visit <http://localhost:3000/> to view the APIs.

Further, checkout [package.json](https://github.com/CodingGardenCommunity/app-backend/blob/develop/package.json) file to learn about(more) available scrips/commands.

### Via Docker

TBD

Happy coding! :)

2019-08-25 08:17 UTC, CodingCreate101 commented
![](https://github.trello.services/images/mini-trello-icon.png) [As a Possible Contributor, I would like to have an up-to-date README.md on app-backend](https://trello.com/c/ZAmqemEW/122-as-a-possible-contributor-i-would-like-to-have-an-up-to-date-readmemd-on-app-backend)

2019-08-26 14:26 UTC, spiray requested changes
Thanks @CodingCreate101!

2019-08-26 14:26 UTC, spiray commented on README.md
> +> **NOTE:** If you find yourself in some trouble going through this, reach out to us on our [Discord server](https://github.com/CodingGardenCommunity/app-wiki/wiki/Getting-Involved).
Should this link directly to `https://discord.gg/bPBuk3N`?

2019-08-26 14:26 UTC, spiray commented on README.md
> +1. Navigate into the project folder and install all of its necessary dependencies with NPM or Yarn.
This should only be done with yarn as we are committing the lock file.

2019-08-26 14:26 UTC, spiray commented on README.md
> +   $ npm install // or yarn install
See previous comment.

2019-08-26 14:26 UTC, spiray commented on README.md
> +1. Once you have MongoDB and `.env` file ready, populate some data in your local Database to work with
Add "seed the local database by running." or something like that.

2019-08-26 14:26 UTC, spiray commented on README.md
> +   If all tests pass(they will), we can safely conclude that setup is complete and its working as expected. Wooh!!
Add a space between pass and (.

2019-08-26 14:26 UTC, spiray commented on README.md
> +1. Once that's done, tap your back. You are ready to start contributing :)
Change :) to 🙂Add, You can run then have npm run dev on the next line and then right to start the server.

2019-08-26 14:29 UTC, CodingCreate101 commented on README.md
> +> **NOTE:** If you find yourself in some trouble going through this, reach out to us on our [Discord server](https://github.com/CodingGardenCommunity/app-wiki/wiki/Getting-Involved).
Yes. But I thought, adding that link kinda introduces them to list of other important things.. that they might wanna know..

2019-08-26 14:30 UTC, CodingCreate101 commented on README.md
> +1. Navigate into the project folder and install all of its necessary dependencies with NPM or Yarn.
Yes, I realized that today. I'll update that.

2019-08-26 14:33 UTC, spiray commented on README.md
> +> **NOTE:** If you find yourself in some trouble going through this, reach out to us on our [Discord server](https://github.com/CodingGardenCommunity/app-wiki/wiki/Getting-Involved).
That makes sense but the preceding verbiage makes it sound like you are linking them directly to the server. You can change it to "here is some info on how to get in touch with us." and use here as a link.

2019-08-26 14:33 UTC, CodingCreate101 commented on README.md
> +1. Once that's done, tap your back. You are ready to start contributing :)
> Add, You can run then have npm run dev on the next line and then right to start the server.

What did you mean? I didn't understand; please explain.

2019-08-26 14:36 UTC, spiray commented on README.md
> +1. Once that's done, tap your back. You are ready to start contributing :)
7. Once that's done, tab your back. You are ready to start contributing🙂You can run -
```sh
npm run dev
```
to start the server. You can now visit http://localhost:3000/ to view the APIs.

Something like that ^

2019-08-26 14:37 UTC, CodingCreate101 commented on README.md
> +> **NOTE:** If you find yourself in some trouble going through this, reach out to us on our [Discord server](https://github.com/CodingGardenCommunity/app-wiki/wiki/Getting-Involved).
Yeah, you are right. I 'll change the way it's described. Thanks! 😃

2019-08-26 16:55 UTC, ewenjo submitted a review, later dismissed

2019-08-26 16:57 UTC, spiray requested changes

2019-08-26 16:57 UTC, spiray commented on README.md
> +Further, checkout [package.json](https://github.com/CodingGardenCommunity/app-backend/blob/develop/package.json) file to learn about (more) available scrips/commands.
scrips -> scripts

2019-08-26 16:57 UTC, spiray commented on README.md
> +   Visit [Yarn download page](https://yarnpkg.com/en/docs/install#windows-stable). Select your Operating system and follow the instructions. It's as easy as eating a 🍰.
The #windows-stable should be removed from the URL.

2019-08-26 16:57 UTC, spiray commented on README.md
> +   If all tests pass (they will), we can safely conclude that setup is complete and its working as expected. 🙌 Wooh!! <br>
Do we want to say "they will!"?

2019-08-26 16:59 UTC, CodingCreate101 commented on README.md
> +   If all tests pass (they will), we can safely conclude that setup is complete and its working as expected. 🙌 Wooh!! <br>
😜 I am imagining a casual tone, like.. they will.. don't worry..

2019-08-26 17:03 UTC, CodingCreate101 commented on README.md
> +Further, checkout [package.json](https://github.com/CodingGardenCommunity/app-backend/blob/develop/package.json) file to learn about (more) available scrips/commands.
Man!! How did you find that! I'll be careful next time.

2019-08-26 17:11 UTC, spiray commented on README.md
> +   If all tests pass (they will), we can safely conclude that setup is complete and its working as expected. 🙌 Wooh!! <br>
I know, but in a way it can discourage contributors if they don't. It doesn't really matter

2019-08-26 17:14 UTC, CodingCreate101 commented on README.md
> +   If all tests pass (they will), we can safely conclude that setup is complete and its working as expected. 🙌 Wooh!! <br>
Hmm.. that's a good point. I'll remove that. We don't wanna cause anxiety by promising it.

2019-08-26 17:19 UTC, spiray approved these changes
Looks good!

2019-08-26 17:40 UTC, ewenjo approved these changes

2019-08-26 17:40 UTC, merged